# mkdir
- name: Make sure directory {{ spotify_apt_repo_key_dst | dirname }} exists
  become: true
  ansible.builtin.file:
    path: "{{ spotify_apt_repo_key_dst | dirname }}"
    mode: u=rwx,g=rx,o=rx
    state: directory

# copy key
- name: Copy repo key to {{ spotify_apt_repo_key_dst }}
  become: true
  ansible.builtin.copy:
    src: spotify.gpg
    dest: "{{ spotify_apt_repo_key_dst }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

# rm list repo
- name: Remove /etc/apt/sources.list.d/spotify.list
  become: true
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/spotify.list
    state: absent

# add repo
- name: Add repo
  become: true
  ansible.builtin.deb822_repository:
    architectures: amd64
    name: spotify
    types: deb
    uris: https://repository.spotify.com
    suites: stable
    components: non-free
    enabled: yes
    signed_by: "{{ spotify_apt_repo_key_dst }}"
  register: __spotify_add_repo # required in main.yml

# only update cache if repo has been added
- name: Update apt cache
  when: __spotify_add_repo.changed
  become: true
  ansible.builtin.apt:
    update_cache: true