---
- name: Spotify role
  tags:
    - spotify
  block:

  # add list repo
  - when: spotify_apt_repo_type == "list"
    ansible.builtin.import_tasks: add_list_repo.yml

  # add sources repo
  - when: spotify_apt_repo_type == "sources"
    ansible.builtin.import_tasks: add_sources_repo.yml

  # debug
  - ansible.builtin.debug:
      msg: 
      - "__spotify_add_repo: {{ __spotify_add_repo }}"

  # install spotify
  - name: Apt spotify-client -> {{ spotify_apt_state }}
    become: true
    ansible.builtin.apt:
      state: "{{ spotify_apt_state }}"
      name: spotify-client